### ISSUE TITLE
External documentation: http://nerditya.com/code/guide-to-neovim/ slightly out of date

### ISSUE THREAD

**Issue by traveish** [adibis/nvim#1]
First of all, Thank you for providing this write-up.  It really helped stream-line my latest attempt at using neovim.

I was wrestling for a little while, when I was trying to append your example "Relative numbering" section to my local vimrc configuration...

```
Function! NumberToggle()
  ...
Endfunc
```

Whenever I restarted neovim with that script, it would fail to initialize.  After a little bit of poking around, I had changed the capital F to a lowercase, and the Endfunc to: endfunction, which resolved my issue.  Just wanted to share what I found, perhaps you can update the guide-to-neovim document, as I am sure others will land on it from Google as I did.  :]

https://github.com/adibis/nvim/blob/master/init.vim#L173

**Comment by adibis** [comment]
Thanks for letting me know. I've been busy so didn't have time to look into this. I will fix it soon, cannot access my development machine from work.

Update: 27th October 2016. Lines changed.
