### ISSUE TITLE
sensible.vim

### ISSUE THREAD

**Issue by justinmk** [adibis/nvim#4]
Just a note to mention that the sensible.vim defaults are already the defaults in nvim:
 https://github.com/neovim/neovim/issues/2676

Also `filetype plugin indent on` and `syntax enable` are not needed, they are enabled by default.

**Comment by adibis** [comment]
Thanks for letting me know. I have removed a bunch of things includeing:
1. Filetype plugin indent on.
2. Syntax enable.
3. nrformats-=octal
4. set smarttab
5. History settings
6. wildmenu 

Since they appear to be defaults now.
